#!/bin/bash


project_path=$HOME/.local/share/mir_phase3

source $project_path/venv/bin/activate

start_crawler(){
	spider=$1
	if test -z $1; then
		spider=articlespider
	fi
	if test -z $2; then
		filename=$HOME/$(date '+%W-%Y.json')
	else
		filename=$2
	fi
	echo "output ---------> $filename"
	echo
	cd $project_path/mir
	if test -f $filename; then
		echo "$filename already exists,"
		read -p "Do you want to overwrite it?! [y|n]: " choice
		re="(yes|y|Y)"
		if [[ $choice =~ $re ]]; then
			rm $filename
		else
			echo "Retry with another output file path"
			exit 1
		fi
	fi
	
	echo "Starting splash container"
	echo

	sudo docker run --rm -d\
		--name=splash \
		-p 5023:5023 \
		-p 8050:8050 \
		-p 8051:8051 \
		scrapinghub/splash \
		--disable-private-mode

	scrapy crawl $spider -o $filename

	echo "Stoping splash container"
	echo

	sudo docker stop splash
}


help(){
	echo "    mir_phase3 [COMMAND] [OPTIONS|ARGUMENTS]"
	echo 
	echo " commands:"
	echo "     crawl <spider name>     starts the crawler"
	echo "	                           specify output file with -o /path/to/output/file option"
	echo "     page-rank               starts PageRank proccess"

}


case $1 in
	crawl | c)
		start_crawler $2 $3
		;;
	*)
		help
		;;
esac
