#!/bin/bash

source venv/bin/activate


start_crawler(){
	spider=$1
	if test -z $1; then
		spider=articlespider
	fi
	cd mir
	filename=$(date '+%W-%Y.json')
	if test -f $filename; then
		rm $filename
	fi
	scrapy crawl $spider -o $filename
}


help(){
	echo "    mir_phase3 [COMMAND] [ARGUMENTS]"
	echo 
	echo " commands:"
	echo "     crawl <spider name>      starts the crawler"
	echo "     page-rank                starts PageRank proccess"

}


case $1 in
	crawl | c)
		start_crawler $2
		;;
	*)
		help
		;;
esac
