#!/bin/bash

project_path=$HOME/.local/share/mir_phase3

source $project_path/venv/bin/activate
start_crawler(){
	spider=$1
	if test -z $1; then
		spider=articlespider
	fi
	if test -z $2; then
		filename=$HOME/$(date '+%W-%Y.json')
	else
		filename=$2
	fi
	echo "output ---------> $filename"
	echo
	cd $project_path/mir
	if test -f $filename; then
		echo "$filename already exists,"
		read -p "Do you want to overwrite it?! [y|n]: " choice
		re="(yes|y|Y)"
		if [[ $choice =~ $re ]]; then
			rm $filename
		else
			echo "Retry with another output file path"
			exit 1
		fi
	fi
	
	echo "Starting splash container"
	echo

	sudo docker run --rm -d\
		--name=splash \
		-p 5023:5023 \
		-p 8050:8050 \
		-p 8051:8051 \
		scrapinghub/splash \
		--disable-private-mode

	scrapy crawl $spider -o $filename

	echo "Stoping splash container"
	echo

	sudo docker stop splash
}


page_rank(){
	alpha=0.85
	pr_value=1
	iteration=5
	if test $2 = "--alpha"; then
		alpha=$3
	elif test $2 = "--pr-value"; then
		pr_value=$3
	elif test $2 = "--it"; then
		iteration=$3
	fi

	if test $4 = "--alpha"; then
		alpha=$5
	elif test $4 = "--pr-value"; then
		pr_value=$5
	elif test $4 = "--it"; then
		iteration=$5
	fi

	output=~/PageRank.json
	if test ! -s $9; then
		output=$9
	fi

	#result=$(python $project_path/mir/page_rank.py --alpha $alpha --pr $pr_value --iteration $iteration)
	result=$(python ./mir/page_rank.py --alpha $alpha --pr $pr_value --iteration $iteration) 
	tee $output << EOF
$result
EOF
}



help(){
	echo "    mir_phase3 [COMMAND] [OPTIONS|ARGUMENTS]"
	echo 
	echo " commands:"
	echo "     crawl <spider name>     starts the crawler"
	echo "	                           specify output file with -o /path/to/output/file option"
	echo "     page-rank               starts PageRank proccess"
	echo "			--alpha: specify alpha"
	echo "			--pr-value: speficy pr-value"
	echo "			--it: specify number of iterations"
	echo
	echo
	echo "	In each commad you can save output with -o option"
}


case $1 in
	crawl | c)
		start_crawler $2 $3
		;;
	page-rank | pr)
		page_rank $@
		;;
	*)
		help
		;;
esac
